language: cpp
script:
- clang++ -Wall -std=c++14 ./main.cpp -o out.exe

deploy:
    provider: script
    skip_cleanup: true
    script:
- curl -T out.exe  -ud2mitryev:$BINTRAY_API_KEY "https://api.bintray.com/content/d2mitryev/otus/hw01/$TRAVIS_BUILD_NUMBER/out.exe;deb_distribution=trusty;deb_component=main;deb_architectrure=amd64;publish=1"

